"""removove api_key from users

Revision ID: 6fe25cf8d400
Revises: d5c7c622752e
Create Date: 2022-03-01 14:58:46.840837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fe25cf8d400'
down_revision = 'd5c7c622752e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'api_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key', sa.VARCHAR(length=511), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
