"""empty message

Revision ID: d5c7c622752e
Revises: 7e8ff7de8948
Create Date: 2022-02-27 18:49:08.470537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c7c622752e'
down_revision = '7e8ff7de8948'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'api_key',
               existing_type=sa.VARCHAR(length=511),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=511), autoincrement=False, nullable=False))
    op.alter_column('users', 'api_key',
               existing_type=sa.VARCHAR(length=511),
               nullable=False)
    # ### end Alembic commands ###
